kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: react-app
  namespace: argocd
  annotations:
    # Assign alias 'react-notes-app' to your image
    argocd-image-updater.argoproj.io/image-list: react-notes-app=worlddev162/react-notes-app

    # Use git write-back method
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds

    # Update strategy for react-notes-app image
    argocd-image-updater.argoproj.io/react-notes-app.update-strategy: semver

spec:
  project: default

  source:
    repoURL: 'https://github.com/gajanan43/react_notes_app_Docker_k8s.git'
    targetRevision: main
    path: argocd/k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: notes-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
